# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0f177d16f06cd98b653b504aadcf5d8270272958fa6b09d8ad45b8fc6b1dd4bad399f843136841cdcebccd4daf23ac0694e0a5f7d8ec323b16d14526c10e3b22

test:
  secret_key_base: 2d1644ea4fb92e6c2eabbc3519160f99b7df91bc49c51ce4424263574a0a68d8a9797cd4b8f6b51924c0ec9c8c94eb1de167c39a43fcc5117c8a2a6153072b9d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
